#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0  -d I II III IV V VI 
bspc monitor HDMI-2 -d VII VIII IX X 

bspc config border_width        0 
bspc config window_gap          10 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Discord desktop='^1'

#Fix Java Applications not displaying properly (wmname package)
wmname LG3D

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

$HOME/.config/polybar/hack/launch.sh
#$HOME/.config/polybar/launch.sh
